name = "Basepack-NF-1.21.1"
author = "jack"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cdfea1e7f24d170d8b67b7c8bb48903db045fdd76c2833048f140c321e03f9f1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
